kind: Service
apiVersion: v1
metadata:
  name: notesapp
  namespace: euc-ns
spec:
  selector:
    app: notesapp
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notesapp
  namespace: euc-ns
spec:
  selector:
      matchLabels:
        app: notesapp
  replicas: 2
  template:
    metadata:
      labels:
        app: notesapp
    spec:
      containers:
        - name: notesapp
          image: venkatadri/springboot-notesapp:10
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
